In [20]:
!pip install tensorflow
import tensorflow as tf
from tensorflow.keras.preprocessing import image 
from tensorflow.keras.layers import GlobalMaxPooling2d

ImportError: cannot import name 'GlobalMaxPooling2d' from 'tensorflow.keras.layers' (C:\Users\bhawn\anaconda3\Lib\site-packages\keras\_tf_keras\keras\layers\__init__.py)

In [21]:
img = image.load_img( "WhatsApp Image 2024-07-24 at 14.03.10.jpeg", target_size=(224,224))

In [22]:
img_array= image.img_to_array(img)

In [23]:
img_array.shape

(224, 224, 3)

In [24]:
import numpy as np
expanded_img_array = np.expand_dims(img_array, axis=0)
print(expanded_img_array.shape)

(1, 224, 224, 3)


In [25]:
expanded_img_array

array([[[[204., 201., 196.],
         [204., 201., 196.],
         [204., 201., 196.],
         ...,
         [206., 203., 196.],
         [206., 203., 196.],
         [206., 203., 196.]],

        [[204., 201., 196.],
         [204., 201., 196.],
         [204., 201., 196.],
         ...,
         [206., 203., 196.],
         [206., 203., 196.],
         [206., 203., 196.]],

        [[204., 201., 196.],
         [204., 201., 196.],
         [204., 201., 196.],
         ...,
         [206., 203., 196.],
         [206., 203., 196.],
         [206., 203., 196.]],

        ...,

        [[203., 197., 197.],
         [203., 197., 197.],
         [203., 197., 197.],
         ...,
         [203., 197., 185.],
         [203., 197., 185.],
         [203., 197., 185.]],

        [[203., 197., 197.],
         [203., 197., 197.],
         [203., 197., 197.],
         ...,
         [203., 197., 185.],
         [203., 197., 185.],
         [203., 197., 185.]],

        [[203., 197., 197.],
       

In [26]:
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input

In [27]:
from tensorflow.keras.layers import GlobalMaxPooling2D

In [28]:
import tensorflow 
model = ResNet50(weights = 'imagenet', include_top = False, input_shape= (224,224,3))
model.trainable = False 

model = tensorflow.keras.Sequential([
    model, 
    GlobalMaxPooling2D()
])

In [13]:
preprocessed_img = preprocess_input(expanded_img_array)
print(preprocessed_img.shape)
preprocessed_img

(1, 224, 224, 3)


array([[[[92.061, 84.221, 80.32 ],
         [92.061, 84.221, 80.32 ],
         [92.061, 84.221, 80.32 ],
         ...,
         [92.061, 86.221, 82.32 ],
         [92.061, 86.221, 82.32 ],
         [92.061, 86.221, 82.32 ]],

        [[92.061, 84.221, 80.32 ],
         [92.061, 84.221, 80.32 ],
         [92.061, 84.221, 80.32 ],
         ...,
         [92.061, 86.221, 82.32 ],
         [92.061, 86.221, 82.32 ],
         [92.061, 86.221, 82.32 ]],

        [[92.061, 84.221, 80.32 ],
         [92.061, 84.221, 80.32 ],
         [92.061, 84.221, 80.32 ],
         ...,
         [92.061, 86.221, 82.32 ],
         [92.061, 86.221, 82.32 ],
         [92.061, 86.221, 82.32 ]],

        ...,

        [[93.061, 80.221, 79.32 ],
         [93.061, 80.221, 79.32 ],
         [93.061, 80.221, 79.32 ],
         ...,
         [81.061, 80.221, 79.32 ],
         [81.061, 80.221, 79.32 ],
         [81.061, 80.221, 79.32 ]],

        [[93.061, 80.221, 79.32 ],
         [93.061, 80.221, 79.32 ],
         [93

In [29]:
model.predict(preprocessed_img)

1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step


array([[ 2.921896  , 12.144642  ,  0.44117117, ...,  6.9471617 ,
         9.127176  , 11.131536  ]], dtype=float32)

In [30]:
model.predict(preprocessed_img).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step


(1, 2048)

In [31]:
model.predict(preprocessed_img).flatten().shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step


(2048,)

In [32]:

from numpy.linalg import norm
model.predict(preprocessed_img).flatten()/norm(model.predict(preprocessed_img).flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step


array([0.01055936, 0.04388919, 0.00159434, ..., 0.02510616, 0.03298445,
       0.04022795], dtype=float32)

In [33]:
from numpy.linalg import norm
norm(model.predict(preprocessed_img).flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step


276.71146

In [35]:
np.sqrt(np.dot(model.predict(preprocessed_img).flatten(),model.predict(preprocessed_img).flatten()))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 199ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step


276.71146